((js-mode . ((js-indent-level . 4)
             (indent-tabs-mode . t)
             ))
 (html-mode . ((sgml-basic-offset . 4)
	       ))
 (css-mode . ((css-indent-offset . 4)
	       ))
 (nil . ((tab-width . 4)
	 ))
 )
